### ISSUE TITLE
test_requirement.txt is missing

### ISSUE THREAD

**Issue by ChenDRAG** [philippe-eecs/IDQL#2]
I run
`pip install -e .`
and got the following error message
```
Obtaining file:///workspace/home/huayu/git/IDQL
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/workspace/home/huayu/git/IDQL/setup.py", line 20, in <module>
          test_requires = read_requirements_file("requirements_test.txt")
        File "/workspace/home/huayu/git/IDQL/setup.py", line 13, in read_requirements_file
          with open(req_file_path) as f:
      FileNotFoundError: [Errno 2] No such file or directory: '/workspace/home/huayu/git/IDQL/requirements_test.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I think the main reason is with the `setup.py` file:
```
    test_requires=test_requires,
    extras_require={
        "test": test_requires,
    },
    license="MIT",

```
I don't know if this is necessary. can I just remove the test requirements?

**Comment by philippe-eecs** [comment]
I just changed the install instructions. Use `pip install -r requirements.txt`

**Comment by ChenDRAG** [comment]
Thanks for the quick response!

**Comment by thu-yao-01-luo** [comment]
Hi, but without `pip install -e .` I find that there is an error reporting that `  File "/home/kairong/IDQL/launcher/examples/train_ddpm_iql_offline.py", line 6, in <module>
    from examples.states.train_diffusion_offline import call_main
ModuleNotFoundError: No module named 'examples.states'`, how do you cope with this problem?

**Comment by philippe-eecs** [comment]
Hi, could you run `export PYTHONPATH="/pathtofolder/IDQL/:$PYTHONPATH"` and set your python path correctly?
